use std::process::Command;

pub struct SyncManager;

impl SyncManager {
    pub fn sync_repositories() -> Result<String, String> {
        Self::run_pacman(&["-Syy", "--noconfirm"], "sync")
    }

    pub fn clean_cache() -> Result<String, String> {
        Self::run_pacman(&["-Sc", "--noconfirm"], "clean cache")
    }

    pub fn backup_mirrorlist() -> Result<String, String> {
        let timestamp = chrono::Local::now().format("%Y%m%d_%H%M%S");
        let backup_path = format!("/etc/pacman.d/mirrorlist.backup.{timestamp}");
        let status = Command::new("pkexec")
            .args(["cp", "/etc/pacman.d/mirrorlist", &backup_path])
            .status()
            .map_err(|e| format!("Failed to execute pkexec: {e}"))?;
        if status.success() {
            Ok(backup_path)
        } else {
            Err("pkexec failed to backup mirrorlist".to_string())
        }
    }

    pub fn generate_share_content(mirrors: &[crate::mirror_manager::Mirror]) -> String {
        let mut s = String::new();
        s.push_str("## Parch Mirror Configuration\n");
        s.push_str(&format!("## Generated by mirrorman on {}\n##\n\n",
            chrono::Local::now().format("%Y-%m-%d %H:%M:%S")));
        let enabled_count = mirrors.iter().filter(|m| m.enabled).count();
        s.push_str(&format!("## {enabled_count} enabled mirror(s)\n\n"));
        for mirror in mirrors {
            if mirror.enabled {
                let url = format!("{}/$repo/os/$arch", mirror.url.trim_end_matches('/'));
                s.push_str(&format!("Server = {url}\n"));
            }
        }
        s
    }

    fn run_pacman(args: &[&str], label: &str) -> Result<String, String> {
        let output = Command::new("pkexec")
            .args(["pacman"])
            .args(args)
            .output()
            .map_err(|e| format!("Failed to execute pacman: {e}"))?;

        if output.status.success() {
            let stdout = String::from_utf8_lossy(&output.stdout).to_string();
            Ok(stdout)
        } else {
            let stderr = String::from_utf8_lossy(&output.stderr).to_string();
            Err(format!("Failed to {label}:\n{stderr}"))
        }
    }
}
