pub struct SyncManager;

impl SyncManager {
    pub fn sync_repositories() -> Result<String, String> {
        Self::run_pacman(&["-Syy", "--noconfirm"], "sync")
    }

    pub fn clean_cache() -> Result<String, String> {
        Self::run_pacman(&["-Sc", "--noconfirm"], "clean cache")
    }

    pub fn backup_mirrorlist() -> Result<String, String> {
        let timestamp = chrono::Local::now().format("%Y%m%d_%H%M%S");
        let backup_path = format!("{}.{timestamp}", crate::mirror_manager::MIRRORLIST_BACKUP);
        let (success, _, stderr) = crate::helper_client::HelperClient::run_command(
            "cp",
            &["/etc/pacman.d/mirrorlist", &backup_path],
        )?;
        if success {
            Ok(backup_path)
        } else {
            Err(format!("Failed to backup mirrorlist: {stderr}"))
        }
    }

    pub fn generate_share_content(mirrors: &[crate::mirror_manager::Mirror]) -> String {
        let mut s = String::new();
        s.push_str("## Parch Mirror Configuration\n");
        s.push_str(&format!("## Generated by mirrorman on {}\n##\n\n",
            chrono::Local::now().format("%Y-%m-%d %H:%M:%S")));
        let enabled_count = mirrors.iter().filter(|m| m.enabled).count();
        s.push_str(&format!("## {enabled_count} enabled mirror(s)\n\n"));
        for mirror in mirrors {
            if mirror.enabled {
                let url = format!("{}/$repo/os/$arch", mirror.url.trim_end_matches('/'));
                s.push_str(&format!("Server = {url}\n"));
            }
        }
        s
    }

    fn run_pacman(args: &[&str], label: &str) -> Result<String, String> {
        let (success, stdout, stderr) = crate::helper_client::HelperClient::run_pacman(args)?;
        if success {
            Ok(stdout)
        } else {
            Err(format!("Failed to {label}:\n{stderr}"))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mirror_manager::Mirror;

    #[test]
    fn test_generate_share_content() {
        let mirrors = vec![
            Mirror {
                url: "https://mirror.parchlinux.ir/".to_string(),
                country: "Iran".to_string(),
                country_code: "IR".to_string(),
                protocol: "https".to_string(),
                speed: Some(10.0),
                last_sync: None,
                enabled: true,
                ipv4: true,
                ipv6: false,
                completion_pct: None,
                score: None,
                duration_avg: None,
                duration_stddev: None,
            },
            Mirror {
                url: "https://mirror.de/".to_string(),
                country: "Germany".to_string(),
                country_code: "DE".to_string(),
                protocol: "https".to_string(),
                speed: Some(50.0),
                last_sync: None,
                enabled: false,
                ipv4: true,
                ipv6: false,
                completion_pct: None,
                score: None,
                duration_avg: None,
                duration_stddev: None,
            },
        ];

        let shared = SyncManager::generate_share_content(&mirrors);
        assert!(shared.contains("## Parch Mirror Configuration"));
        assert!(shared.contains("## 1 enabled mirror(s)"));
        assert!(shared.contains("Server = https://mirror.parchlinux.ir/$repo/os/$arch"));
        assert!(!shared.contains("mirror.de"));
    }
}
